version: 2.1
orbs:
  sixrs-gke: sixriversystems/sixrs-gke@2
jobs:
  setup:
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json"}}
            - dependency-cache-
      - run:
          name: Install node dependencies
          command: |
            npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - .
  publish:
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: test
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - sixrs-gke/npm-public-publish
  test:
    docker:
      - image: node:10
        environment:
          NODE_ENV: test
          MOCHA_OPTS: --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/junit/mocha/mocha.xml
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: npm test
          command: |
            npm test

workflows:
  version: 2
  test_and_publish:
    jobs:
      - setup:
          context: 6rs-public-npm
      - test:
          context: 6rs-public-npm
          requires:
            - setup
      - publish:
          context: 6rs-public-npm
          requires:
            - test
